stages:
  - build

build-test-upload:
  extends: .cuda-build-test-upload

include:
  - project: 'biocad/bcd-ci-common'
    ref: akhoroshev/update-cuda-pipelines
    file: '/build/cuda/build-test-upload.yaml'
