stages:
  - build

build-test-upload-branches:
  extends: .cuda-build-test-upload
  only:
    - branches
  except:
    - master

build-test-upload-tags:
  extends: .cuda-build-test-upload
  only:
    - tags

include:
  - project: 'biocad/bcd-ci-common'
    ref: akhoroshev/update-cuda-pipelines
    file: '/build/cuda/build-test-upload.yaml'
